export const SPLASH_SCREEN_ROUTE = 'SPLASH_SCREEN_ROUTE';
export const HOME_SCREEN_ROUTE = 'HOME_SCREEN_ROUTE';
export const BAG_SCREEN_ROUTE = 'BAG_SCREEN_ROUTE';
export const SHOP_SCREEN_ROUTE = 'SHOP_SCREEN_ROUTE';
export const PROFILE_SCREEN_ROUTE = 'PROFILE_SCREEN_ROUTE';
export const FAVOURITE_SCREEN_ROUTE = 'FAVOURITE_SCREEN_ROUTE';
export const BOTTOM_TAB_NAVIGATION = 'BOTTOM_TAB_NAVIGATION';
